import { useEffect, useState } from "react";
import styles from '@/styles/Home.module.css'
import Head from "next/head";
import { Container } from "react-dom";

function Home() {
    let [ContainersPar, setContainersP] = useState<Container[]>();

    useEffect(()=>{

    },[])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className={styles.menuBox}>
                <button>Импорт</button>
            </nav>
            <main className={styles.mainBox}>
                <div>

                </div>
            </main>
        </>
    );
}

export default Home;

function fillContainers(Id : string)
{
    if(Id)
    {

    }
    else
    {
        
    }
}