import { useEffect, useState } from "react";
import styles from '@/styles/Home.module.css'
import Head from "next/head";
import Container from "lib/Container";
import Substance from "lib/Substance";
import { from } from "linq-to-typescript"

function Home() {
    //Показываемые контейнеры
    let [ContList, setContList] = useState<Container[]>([]);
    //вещества открытого контейнера
    let [SubstList, setSubstList] = useState<Substance[]>([]);
    //история посещения контейнера
    let [HistoryCont, setSubstHist] = useState<Container[]>([]);
    function BuildChildrens(data: Container[], Id: string) {
        let NewLoudData: Container;
        let Conts: Container[] = data;
        NewLoudData = from(ContList).where(x => x.Id === Id).first() as Container;
        setSubstHist(prevHistoryCont => prevHistoryCont.concat(NewLoudData));
        Conts = Conts.filter(x => x.Id !== Id);
        setContList(Conts);
        console.log(HistoryCont);
    }

    async function OpenClickHandler(Id: string) {
        console.log(Id);
        const response = await fetch(`http://localhost:3000/api/Cont/${Id}`);
        const data = await response.json();
        BuildChildrens(data, Id);
    }

    useEffect(() => {
        fetch("http://localhost:3000/api/parrentcontainers")
            .then(async res => await res.json())
            .then(data => setContList(data));
    }, [])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className={styles.menuBox}>
                <button>Импорт</button>
            </nav>
            <div className={styles.menuBox}>
                <button>Назад</button>
            </div>
            <main className={styles.mainBox}>
                <div className={styles.substContFree}>
                    Text
                </div>
                <div className={styles.contMain}>
                    {
                        ContList?.map((item) => {

                            return (
                                <div key={item.Id} className={styles.containerDiv}>
                                    <button onClick={() => OpenClickHandler(item.Id)}>&gt;</button>
                                    <h1>{item.Name}</h1>
                                </div>
                            );
                        })
                    }
                </div>
            </main>
        </>
    );
}

export default Home;